### ISSUE TITLE
Potential performance issue: .fillna memory issue in pandas below 1.4.2 version

### ISSUE THREAD

**Issue by TendouArisu** [xingyaoww/code-act#3]
**Issue Description:**

Hello.
I have discovered a performance degradation in the `.fillna` function of pandas version 1.4.1 and below 1.4.2. And I notice the repository depends on pandas 1.4.1 in `scripts/eval/science-world/requirements.txt`.  I am not sure whether this performance problem in pandas will affect this repository. I found some discussions on pandas GitHub related to this issue, including [#46149](https://github.com/pandas-dev/pandas/issues/46149) and [#46204](https://github.com/pandas-dev/pandas/pull/46204).
I also found that `scripts/data/interaction/collection/convert_outputs.ipynb` and `scripts/eval/mint-bench/convert_outputs.py` used the influenced api. There may be more files using the influenced api and pandas version below 1.4.2.

**Suggestion**

I would recommend considering an upgrade to a different version of pandas >= 1.4.2 or exploring other solutions to optimize the performance.
Any other workarounds or solutions would be greatly appreciated.
Thank you!

**Comment by xingyaoww** [comment]
Hi @TendouArisu, thanks for the issue! I just removed the file `scripts/eval/science-world/requirements.txt` since we did not use it to setup environment (see [here](https://github.com/xingyaoww/code-act/blob/ce451422e34dd696dda6f523baebdc0d9c18a571/scripts/eval/setup_env.sh#L31-L34)). The code should work fine if you use a newer version of pandas. Please let me know if you encountered more issues!
